# Generated by Django 5.2.7 on 2026-10-03 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_checklistitem_checklist'),
        ('sales', '0015_invoice_advance_adjustment_invoice_is_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Signed contract this event was created from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='sales.contract'),
        ),
    ]
