# Generated by Django 5.2.7 on 2026-10-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_userloginsession_idle_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('inquiry_assigned', 'Inquiry assigned'), ('lead_follow_up', 'Lead follow-up'), ('deal_expected_close', 'Deal expected close'), ('proposal_due', 'Proposal due'), ('contract_ending', 'Contract ending'), ('invoice_due', 'Invoice due'), ('project_assigned', 'Project assigned'), ('project_due', 'Project due'), ('project_completed_review_pending', 'Project completed - review pending'), ('task_assigned', 'Task assigned'), ('task_due', 'Task due'), ('deliverable_assigned', 'Deliverable assigned'), ('deliverable_due', 'Deliverable due'), ('event_reminder', 'Event reminder'), ('event_needs_project', 'Event needs a project')], max_length=64),
        ),
    ]
