# Generated by Django 5.2.7 on 2026-10-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_packageitem_options_packageitem_sort_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('sort_order', 'name')},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('sort_order', 'name')},
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bundle price. Leave blank to charge the sum of its services.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short line printed under the package name in proposals.', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='price_unit',
            field=models.CharField(choices=[('event', 'per event'), ('day', 'per day'), ('hour', 'per hour'), ('item', 'per item'), ('album', 'per album'), ('person', 'per person'), ('fixed', 'fixed')], default='event', help_text='How the price is charged, e.g. per event or per album.', max_length=16),
        ),
        migrations.AddField(
            model_name='service',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='summary',
            field=models.CharField(blank=True, help_text='One line printed under this service in proposals and contracts.', max_length=255),
        ),
    ]
