# Generated by Django 5.2.7 on 2026-10-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_inquiry_wedding_city_inquiry_wedding_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('proposal_accepted', 'Proposal Accepted'), ('lost', 'Lost'), ('converted_to_deal', 'Converted to Deal'), ('converted_to_client', 'Converted to Client')], default='new', max_length=50),
        ),
    ]
