# Generated by Django 5.2.7 on 2026-10-04 15:06

from django.db import migrations, models


def fill_state_from_wedding(apps, schema_editor):
    """Older leads only had a wedding state; start the new state from it."""
    from common.geo import INDIAN_STATES

    Lead = apps.get_model("crm", "Lead")
    states = {state.lower(): state for state in INDIAN_STATES}
    for lead in Lead.objects.filter(state="").exclude(wedding_state="").only("id", "wedding_state", "wedding_country"):
        if (lead.wedding_country or "India") != "India":
            continue
        state = states.get(lead.wedding_state.strip().lower())
        if state:
            Lead.objects.filter(pk=lead.pk).update(state=state)


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_alter_lead_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="country",
            field=models.CharField(blank=True, default="India", max_length=100),
        ),
        migrations.AddField(
            model_name="lead",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(fill_state_from_wedding, migrations.RunPython.noop),
    ]
