# Generated by Django 5.2.7 on 2026-10-03 18:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_invoice_discount_invoice_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='advance_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Advance already received on this deal, deducted from the total.', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_advance',
            field=models.BooleanField(default=False, help_text='Booking advance collected before the contract is signed.'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('advance_received', 'Advance Received'), ('contract_sent', 'Contract Sent'), ('won', 'Won'), ('lost', 'Lost'), ('on_hold', 'On Hold')], default='new', max_length=32),
        ),
    ]
