# Generated by Django 5.2.7 on 2026-10-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_invoice_advance_adjustment_invoice_is_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='intro',
            field=models.TextField(blank=True, help_text='Personal note to the couple, printed on the cover letter page.'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='terms',
            field=models.TextField(blank=True, help_text='One condition per line. Leave blank to use the standard Ocean Clouds terms.'),
        ),
    ]
