# Generated by Django 5.2.7 on 2026-10-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0017_payment_invoice_protect"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="next_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("call", "Call"),
                    ("whatsapp", "WhatsApp"),
                    ("email", "Email"),
                    ("meeting", "Meeting"),
                    ("video_call", "Video call"),
                    ("send_proposal", "Send proposal"),
                    ("collect_advance", "Collect advance"),
                    ("send_contract", "Send contract"),
                    ("follow_up", "Follow up"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="next_action_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="next_action_note",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
