# Generated by Django 5.2.7 on 2026-10-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0018_deal_next_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesDocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal_note",
                    models.TextField(
                        blank=True,
                        help_text="Opening letter of every proposal. A proposal's own note replaces it.",
                        verbose_name="proposal personal note",
                    ),
                ),
                (
                    "proposal_terms",
                    models.TextField(
                        blank=True,
                        help_text="One condition per line. The payment split line is added for you.",
                        verbose_name="proposal terms",
                    ),
                ),
                (
                    "contract_note",
                    models.TextField(
                        blank=True,
                        help_text="Short paragraph under the parties on the first page.",
                        verbose_name="contract note",
                    ),
                ),
                (
                    "contract_terms",
                    models.TextField(
                        blank=True,
                        help_text="One condition per line. A contract's own terms replace these.",
                        verbose_name="contract terms",
                    ),
                ),
                (
                    "good_to_know",
                    models.TextField(
                        blank=True,
                        help_text="Practical notes for the couple, one per line.",
                        verbose_name="good to know",
                    ),
                ),
                (
                    "payment_terms",
                    models.TextField(
                        blank=True,
                        help_text="One per line, shown with the payment schedule.",
                        verbose_name="payment terms",
                    ),
                ),
                (
                    "advance_percent",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="booking advance %"
                    ),
                ),
                (
                    "event_percent",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="on the event day %"
                    ),
                ),
                (
                    "delivery_percent",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="on delivery %"
                    ),
                ),
            ],
            options={
                "verbose_name": "proposal & contract template",
                "verbose_name_plural": "proposal & contract template",
            },
        ),
    ]
