# Generated by Django 5.2.7 on 2026-10-04 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_invoiced_contracts_approved(apps, schema_editor):
    # Contracts that already have their invoice went through the old manual
    # steps; they are not waiting for approval.
    Contract = apps.get_model("sales", "Contract")
    for contract in Contract.objects.filter(
        status="signed", approved_at__isnull=True, invoices__is_advance=False
    ).distinct():
        contract.approved_at = contract.updated_at
        contract.save(update_fields=["approved_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0019_sales_document_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_contracts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(mark_invoiced_contracts_approved, migrations.RunPython.noop),
    ]
